# 默认导航配置（请勿直接修改）。
# 建议复制到 config/user/navigation.yml 并按需调整。
# 规则：
# - 每个导航项的 id 必须唯一，并与 pages/<id>.yml 对应
# - 全局仅允许一个 active: true 作为默认激活页面
- name: 首页        # 菜单名称
  icon: fas fa-home  # Font Awesome 图标类
  id: home           # 页面标识符（唯一，需与 pages/home.yml 对应）
  active: true       # 是否默认激活（全局仅一个 true）
- name: 项目
  icon: fas fa-project-diagram
  id: projects
- name: 文章
  icon: fas fa-book
  id: articles
- name: 朋友
  icon: fas fa-users
  id: friends
- name: 书签
  icon: fas fa-bookmark
  id: bookmarks
