# 默认页面配置（请勿直接修改）。
# 建议复制到 config/user/pages/articles.yml 并按需调整。
title: 技术文章                 # 页面标题
subtitle: 分享我的技术文章和学习笔记  # 页面副标题

# 指定使用的模板文件名，现有页面模板可见 templates/pages（不含 .hbs）
template: articles

# 页面分类与站点列表
categories:
  - name: 最新文章
    icon: fas fa-pen  # 分类图标
    sites:
      - name: Vue3最佳实践            # 站点名称
        icon: fab fa-vuejs           # 文章/站点图标
        description: Vue3组合式API的使用技巧  # 摘要
        url: "#"                     # 链接（示例）
      - name: JavaScript进阶
        icon: fab fa-js
        description: JavaScript高级特性解析
        url: "#"
      - name: Git使用技巧
        icon: fab fa-git-alt
        description: Git常用命令和工作流
        url: "#"
      - name: Docker入门
        icon: fab fa-docker
        description: Docker基础知识和实践
        url: "#"
  - name: 学习笔记
    icon: fas fa-book
    sites:
      - name: React Hooks
        icon: fab fa-react
        description: React Hooks最佳实践
        url: "#"
      - name: Node.js实战
        icon: fab fa-node-js
        description: Node.js服务端开发笔记
        url: "#" 
