# 四层级嵌套书签配置示例
# 展示分类 -> 子分类 -> 分组 -> 网站的四层结构
# 说明：该页面通常由“书签导入工具”自动生成，手工修改时请保持字段结构一致。
title: 我的书签
subtitle: 从浏览器导入的书签收藏

# 指定使用的模板文件名，现有页面模板可见 templates/pages（不含 .hbs）
template: bookmarks

categories:
  - name: '技术资源'
    icon: 'fas fa-laptop-code'
    subcategories:
      - name: '前端开发'
        icon: 'fas fa-code'
        groups:
          - name: '框架库'
            icon: 'fas fa-cube'
            sites:
              - name: 'React'
                url: 'https://reactjs.org/'
                icon: 'fab fa-react'
                description: 'React官方文档'
              - name: 'Vue.js'
                url: 'https://vuejs.org/'
                icon: 'fab fa-vuejs'
                description: 'Vue.js官方文档'
              - name: 'Angular'
                url: 'https://angular.io/'
                icon: 'fab fa-angular'
                description: 'Angular官方文档'
              - name: 'Svelte'
                url: 'https://svelte.dev/'
                icon: 'fas fa-fire'
                description: 'Svelte官方文档'
          - name: '状态管理'
            icon: 'fas fa-database'
            sites:
              - name: 'Redux'
                url: 'https://redux.js.org/'
                icon: 'fas fa-database'
                description: 'Redux状态管理'
              - name: 'Vuex'
                url: 'https://vuex.vuejs.org/'
                icon: 'fas fa-database'
                description: 'Vue状态管理'
              - name: 'MobX'
                url: 'https://mobx.js.org/'
                icon: 'fas fa-react'
                description: '响应式状态管理'
          - name: '构建工具'
            icon: 'fas fa-tools'
            sites:
              - name: 'Webpack'
                url: 'https://webpack.js.org/'
                icon: 'fas fa-cube'
                description: '模块打包工具'
              - name: 'Vite'
                url: 'https://vitejs.dev/'
                icon: 'fas fa-bolt'
                description: '下一代前端构建工具'
              - name: 'Rollup'
                url: 'https://rollupjs.org/'
                icon: 'fas fa-compress'
                description: '模块打包器'
      - name: '后端开发'
        icon: 'fas fa-server'
        groups:
          - name: 'Node.js生态'
            icon: 'fab fa-node-js'
            sites:
              - name: 'Express'
                url: 'https://expressjs.com/'
                icon: 'fas fa-server'
                description: 'Node.js Web框架'
              - name: 'Koa'
                url: 'https://koajs.com/'
                icon: 'fas fa-leaf'
                description: '下一代Node.js框架'
              - name: 'NestJS'
                url: 'https://nestjs.com/'
                icon: 'fas fa-home'
                description: 'Node.js企业级框架'
          - name: 'Python框架'
            icon: 'fab fa-python'
            sites:
              - name: 'Django'
                url: 'https://www.djangoproject.com/'
                icon: 'fas fa-python'
                description: 'Python Web框架'
              - name: 'Flask'
                url: 'https://flask.palletsprojects.com/'
                icon: 'fas fa-flask'
                description: 'Python微框架'
              - name: 'FastAPI'
                url: 'https://fastapi.tiangolo.com/'
                icon: 'fas fa-bolt'
                description: '现代Python Web框架'
          - name: '数据库ORM'
            icon: 'fas fa-database'
            sites:
              - name: 'Prisma'
                url: 'https://www.prisma.io/'
                icon: 'fas fa-database'
                description: '下一代数据库工具'
              - name: 'TypeORM'
                url: 'https://typeorm.io/'
                icon: 'fas fa-database'
                description: 'TypeScript ORM'
              - name: 'SQLAlchemy'
                url: 'https://www.sqlalchemy.org/'
                icon: 'fas fa-database'
                description: 'Python SQL工具包'

  - name: '设计资源'
    icon: 'fas fa-palette'
    subcategories:
      - name: 'UI设计工具'
        icon: 'fas fa-paint-brush'
        groups:
          - name: '原型设计'
            icon: 'fas fa-drafting-compass'
            sites:
              - name: 'Figma'
                url: 'https://www.figma.com/'
                icon: 'fab fa-figma'
                description: '协作式UI设计工具'
              - name: 'Sketch'
                url: 'https://www.sketch.com/'
                icon: 'fab fa-sketch'
                description: 'Mac平台UI设计工具'
              - name: 'Adobe XD'
                url: 'https://www.adobe.com/products/xd.html'
                icon: 'fab fa-adobe'
                description: 'Adobe UI设计工具'
          - name: '设计系统'
            icon: 'fas fa-th-large'
            sites:
              - name: 'Ant Design'
                url: 'https://ant.design/'
                icon: 'fas fa-th'
                description: '企业级UI设计语言'
              - name: 'Material Design'
                url: 'https://material.io/design'
                icon: 'fas fa-cube'
                description: 'Google设计系统'
              - name: 'Bootstrap'
                url: 'https://getbootstrap.com/'
                icon: 'fab fa-bootstrap'
                description: '响应式CSS框架'
          - name: '交互设计'
            icon: 'fas fa-hand-pointer'
            sites:
              - name: 'Principle'
                url: 'https://principleformac.com/'
                icon: 'fas fa-magic'
                description: '交互设计工具'
              - name: 'Framer'
                url: 'https://www.framer.com/'
                icon: 'fas fa-mobile-alt'
                description: '交互式设计工具'
              - name: 'ProtoPie'
                url: 'https://www.protopie.io/'
                icon: 'fas fa-chart-pie'
                description: '原型制作工具'
      - name: '视觉资源'
        icon: 'fas fa-image'
        groups:
          - name: '图标库'
            icon: 'fas fa-icons'
            sites:
              - name: 'Font Awesome'
                url: 'https://fontawesome.com/'
                icon: 'fab fa-font-awesome'
                description: '图标库'
              - name: 'Iconfont'
                url: 'https://www.iconfont.cn/'
                icon: 'fas fa-icons'
                description: '阿里巴巴图标库'
              - name: 'Feather Icons'
                url: 'https://feathericons.com/'
                icon: 'fas fa-feather'
                description: '简洁的图标库'
          - name: '插画资源'
            icon: 'fas fa-paint-brush'
            sites:
              - name: 'UnDraw'
                url: 'https://undraw.co/'
                icon: 'fas fa-palette'
                description: '开源插画库'
              - name: 'Illustrations.co'
                url: 'https://illustrations.co/'
                icon: 'fas fa-image'
                description: '插画资源'
              - name: 'Storyset'
                url: 'https://storyset.com/'
                icon: 'fas fa-book'
                description: '动画插画库'
          - name: '配色方案'
            icon: 'fas fa-palette'
            sites:
              - name: 'Coolors'
                url: 'https://coolors.co/'
                icon: 'fas fa-palette'
                description: '在线配色方案生成器'
              - name: 'Adobe Color'
                url: 'https://color.adobe.com/'
                icon: 'fab fa-adobe'
                description: 'Adobe配色工具'
              - name: 'Paletton'
                url: 'https://paletton.com/'
                icon: 'fas fa-palette'
                description: '配色方案设计工具'

  - name: '开发工具'
    icon: 'fas fa-tools'
    subcategories:
      - name: '编程工具'
        icon: 'fas fa-code'
        groups:
          - name: '代码编辑器'
            icon: 'fas fa-code'
            sites:
              - name: 'Visual Studio Code'
                url: 'https://code.visualstudio.com/'
                icon: 'fas fa-code'
                description: '微软代码编辑器'
              - name: 'Sublime Text'
                url: 'https://www.sublimetext.com/'
                icon: 'fas fa-file-code'
                description: '轻量级代码编辑器'
              - name: 'WebStorm'
                url: 'https://www.jetbrains.com/webstorm/'
                icon: 'fab fa-js'
                description: 'JetBrains前端IDE'
          - name: '版本控制'
            icon: 'fas fa-code-branch'
            sites:
              - name: 'GitHub'
                url: 'https://github.com/'
                icon: 'fab fa-github'
                description: '代码托管平台'
              - name: 'GitLab'
                url: 'https://gitlab.com/'
                icon: 'fab fa-gitlab'
                description: 'Git代码管理平台'
              - name: 'Bitbucket'
                url: 'https://bitbucket.org/'
                icon: 'fab fa-bitbucket'
                description: 'Atlassian代码托管'
          - name: '调试工具'
            icon: 'fas fa-bug'
            sites:
              - name: 'Chrome DevTools'
                url: 'https://developers.google.com/web/tools/chrome-devtools'
                icon: 'fab fa-chrome'
                description: 'Chrome开发者工具'
              - name: 'Firefox DevTools'
                url: 'https://developer.mozilla.org/en-US/docs/Tools'
                icon: 'fab fa-firefox'
                description: 'Firefox开发者工具'
              - name: 'Postman'
                url: 'https://www.postman.com/'
                icon: 'fas fa-paper-plane'
                description: 'API测试工具'
      - name: '部署运维'
        icon: 'fas fa-server'
        groups:
          - name: '云服务'
            icon: 'fas fa-cloud'
            sites:
              - name: 'AWS'
                url: 'https://aws.amazon.com/'
                icon: 'fab fa-aws'
                description: '亚马逊云服务'
              - name: 'Azure'
                url: 'https://azure.microsoft.com/'
                icon: 'fab fa-microsoft'
                description: '微软云服务'
              - name: 'Google Cloud'
                url: 'https://cloud.google.com/'
                icon: 'fab fa-google'
                description: '谷歌云服务'
          - name: '容器化'
            icon: 'fas fa-cube'
            sites:
              - name: 'Docker'
                url: 'https://www.docker.com/'
                icon: 'fab fa-docker'
                description: '容器化平台'
              - name: 'Kubernetes'
                url: 'https://kubernetes.io/'
                icon: 'fas fa-dharmachakra'
                description: '容器编排系统'
              - name: 'Podman'
                url: 'https://podman.io/'
                icon: 'fas fa-cube'
                description: '无守护进程容器引擎'
          - name: 'CI/CD'
            icon: 'fas fa-infinity'
            sites:
              - name: 'GitHub Actions'
                url: 'https://github.com/features/actions'
                icon: 'fab fa-github'
                description: 'GitHub自动化工具'
              - name: 'Jenkins'
                url: 'https://www.jenkins.io/'
                icon: 'fas fa-infinity'
                description: '开源自动化服务器'
              - name: 'GitLab CI'
                url: 'https://docs.gitlab.com/ee/ci/'
                icon: 'fab fa-gitlab'
                description: 'GitLab CI/CD工具'